#DROP TABLE IF EXISTS ValOne;
DROP TABLE IF EXISTS Reading;
DROP TABLE IF EXISTS Unit;
DROP TABLE IF EXISTS UnitType;
DROP TABLE IF EXISTS Proj;
DROP TABLE IF EXISTS Cust;
DROP TABLE IF EXISTS Loc;
DROP TABLE IF EXISTS Mat;

